# Generated by Django 2.2 on 2020-08-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_company',
            field=models.CharField(choices=[('Master', 'Master'), ('Visa', 'Visa'), ('Maestro', 'Maestro'), ('Others', 'Others')], default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
