# Generated by Django 2.2 on 2021-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_select_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select_plan',
            field=models.CharField(blank=True, choices=[('Premium', 'Premium'), ('Luxury', 'Luxury'), ('VIP', 'VIP'), ('VIP Luxury', 'VIP Luxury'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Sapphire', 'Sapphire'), ('Emerald', 'Emerald'), ('Tanzanite', 'Tanzanite'), ('Ruby', 'Ruby')], max_length=40, null=True),
        ),
    ]
