# Generated by Django 2.2 on 2020-04-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
