# Generated by Django 2.2 on 2020-08-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200818_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountupgrade',
            name='back_page',
        ),
        migrations.RemoveField(
            model_name='accountupgrade',
            name='front_page',
        ),
        migrations.AddField(
            model_name='accountupgrade',
            name='document',
            field=models.FileField(default='', upload_to='docs/'),
        ),
    ]
