# Generated by Django 2.2 on 2020-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200603_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='swift_code',
            field=models.CharField(max_length=15),
        ),
    ]
