# Generated by Django 2.2 on 2020-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bitcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
