# Generated by Django 2.2 on 2020-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_accountupgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountupgrade',
            name='name',
        ),
        migrations.AddField(
            model_name='accountupgrade',
            name='document',
            field=models.FileField(default='', upload_to='docs'),
            preserve_default=False,
        ),
    ]
