# Generated by Django 2.2 on 2020-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200805_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountupgrade',
            name='verify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
